package com.dao;

import com.vo.DesignTempletIndex;
import com.vo.DesignTempletIndexExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DesignTempletIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Sun Apr 08 13:14:19 CST 2018
     */
    int countByExample(DesignTempletIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Sun Apr 08 13:14:19 CST 2018
     */
    int deleteByExample(DesignTempletIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Sun Apr 08 13:14:19 CST 2018
     */
    int deleteByPrimaryKey(String designTempletIndexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Sun Apr 08 13:14:19 CST 2018
     */
    int insert(DesignTempletIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Sun Apr 08 13:14:19 CST 2018
     */
    int insertSelective(DesignTempletIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Sun Apr 08 13:14:19 CST 2018
     */
    List<DesignTempletIndex> selectByExample(DesignTempletIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Sun Apr 08 13:14:19 CST 2018
     */
    DesignTempletIndex selectByPrimaryKey(String designTempletIndexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Sun Apr 08 13:14:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") DesignTempletIndex record, @Param("example") DesignTempletIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Sun Apr 08 13:14:19 CST 2018
     */
    int updateByExample(@Param("record") DesignTempletIndex record, @Param("example") DesignTempletIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Sun Apr 08 13:14:19 CST 2018
     */
    int updateByPrimaryKeySelective(DesignTempletIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Sun Apr 08 13:14:19 CST 2018
     */
    int updateByPrimaryKey(DesignTempletIndex record);

    /*获取design_templet_index表数据，首先按照design_templet_index_sign升序排序，然后按照design_templet_index_order升序排序*/
	List<DesignTempletIndex> selectByDesignTempletIndexIdOrderByDesignTempletIndexSignDesignTempletIndexOrder(
			String designTempletId);
}