package com.vo;

import java.io.Serializable;

@SuppressWarnings("serial")
public class DesignSingleOption implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_single_option.design_single_option_id
     *
     * @mbggenerated Tue Apr 10 16:03:01 CST 2018
     */
    private String designSingleOptionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_single_option.design_single_id
     *
     * @mbggenerated Tue Apr 10 16:03:01 CST 2018
     */
    private String designSingleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_single_option.design_single_order
     *
     * @mbggenerated Tue Apr 10 16:03:01 CST 2018
     */
    private Integer designSingleOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_single_option.design_single_option_content
     *
     * @mbggenerated Tue Apr 10 16:03:01 CST 2018
     */
    private String designSingleOptionContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_single_option.design_single_option_id
     *
     * @return the value of design_single_option.design_single_option_id
     *
     * @mbggenerated Tue Apr 10 16:03:01 CST 2018
     */
    public String getDesignSingleOptionId() {
        return designSingleOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_single_option.design_single_option_id
     *
     * @param designSingleOptionId the value for design_single_option.design_single_option_id
     *
     * @mbggenerated Tue Apr 10 16:03:01 CST 2018
     */
    public void setDesignSingleOptionId(String designSingleOptionId) {
        this.designSingleOptionId = designSingleOptionId == null ? null : designSingleOptionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_single_option.design_single_id
     *
     * @return the value of design_single_option.design_single_id
     *
     * @mbggenerated Tue Apr 10 16:03:01 CST 2018
     */
    public String getDesignSingleId() {
        return designSingleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_single_option.design_single_id
     *
     * @param designSingleId the value for design_single_option.design_single_id
     *
     * @mbggenerated Tue Apr 10 16:03:01 CST 2018
     */
    public void setDesignSingleId(String designSingleId) {
        this.designSingleId = designSingleId == null ? null : designSingleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_single_option.design_single_order
     *
     * @return the value of design_single_option.design_single_order
     *
     * @mbggenerated Tue Apr 10 16:03:01 CST 2018
     */
    public Integer getDesignSingleOrder() {
        return designSingleOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_single_option.design_single_order
     *
     * @param designSingleOrder the value for design_single_option.design_single_order
     *
     * @mbggenerated Tue Apr 10 16:03:01 CST 2018
     */
    public void setDesignSingleOrder(Integer designSingleOrder) {
        this.designSingleOrder = designSingleOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_single_option.design_single_option_content
     *
     * @return the value of design_single_option.design_single_option_content
     *
     * @mbggenerated Tue Apr 10 16:03:01 CST 2018
     */
    public String getDesignSingleOptionContent() {
        return designSingleOptionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_single_option.design_single_option_content
     *
     * @param designSingleOptionContent the value for design_single_option.design_single_option_content
     *
     * @mbggenerated Tue Apr 10 16:03:01 CST 2018
     */
    public void setDesignSingleOptionContent(String designSingleOptionContent) {
        this.designSingleOptionContent = designSingleOptionContent == null ? null : designSingleOptionContent.trim();
    }
}